name: Convert CustomPinyinDictionary
on:
  workflow_dispatch:
  schedule:
    - cron: '5 7 1 * *' # runs monthlys
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check the version of CustomPinyinDictionary
        id: check-version
        run: |
          latest=$(gh --repo wuhgit/CustomPinyinDictionary \
            release view --json body --jq ".body" | head -n 1 | cut -c 4-12)
          now=$(gh --repo "$GITHUB_REPOSITORY" \
            release list --json tagName --jq ".[0].tagName" 2>/dev/null || echo "")

          if [ "$now" != "$latest" ]; then
            echo "VERSION=$latest" >> "$GITHUB_ENV"
            echo "NEED_UPDATE=1" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump the txt format dictionary
        if: ${{ steps.check-version.outputs.NEED_UPDATE == '1' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libime-bin
          gh --repo wuhgit/CustomPinyinDictionary \
            release download -p "CustomPinyinDictionary_Fcitx.dict"
          libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt
          gh --repo "$GITHUB_REPOSITORY" \
            release create "$VERSION" ./CustomPinyinDictionary_Fcitx.txt -t "$VERSION"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
