name: Convert CustomPinyinDictionary
on:
  workflow_dispatch:
  schedule:
    - cron: '5 7 1 * *' # runs monthlys
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check the version of CustomPinyinDictionary
        id: check-version
        run: |
          now=$(gh --repo "$GITHUB_REPOSITORY" \
            release list --json tagName --jq ".[0].tagName" 2>/dev/null || echo "")
          latest=$(gh --repo wuhgit/CustomPinyinDictionary \
            release view --json body --jq ".body" | head -n 1 | cut -c 4-12)

          echo "NOW=$now"
          echo "LATEST=$latest"

          if [ "$now" != "$latest" ]; then
            echo "Versions are mismatch"
            echo "VERSION=$latest" >> "$GITHUB_ENV"
            echo "NEED_UPDATE=1" >> "$GITHUB_OUTPUT"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download ImewlConverter
        if: ${{ steps.check-version.outputs.NEED_UPDATE == '1' }}
        run: |
          wget https://github.com/studyzy/imewlconverter/releases/latest/download/imewlconverter_linux-x64.tar.gz
          tar -xvf imewlconverter_linux-x64.tar.gz
          install -Dm755 ImeWlConverterCmd -t /usr/local/bin

      - name: Bump the txt format dictionary
        if: ${{ steps.check-version.outputs.NEED_UPDATE == '1' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libime-bin
          gh --repo wuhgit/CustomPinyinDictionary \
            release download -p "CustomPinyinDictionary_Fcitx.dict"
          libime_pinyindict -d CustomPinyinDictionary_Fcitx.dict CustomPinyinDictionary_Fcitx.txt
          ImeWlConverterCmd -i:libpy CustomPinyinDictionary_Fcitx.txt -o:rime CustomPinyinDictionary.dict.yaml
          gh --repo "$GITHUB_REPOSITORY" \
            release create "$VERSION" ./CustomPinyinDictionary_Fcitx.txt -t "$VERSION" \
            -n "Auto-generating rime version of CustomPinyinDictionary"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
